DROP TABLE IF EXISTS `qb_labelhy`;
CREATE TABLE IF NOT EXISTS `qb_labelhy` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT '自动增值ID',
  `name` varchar(32) NOT NULL DEFAULT '' COMMENT '标签区分符',
  `pagename` varchar(32) NOT NULL COMMENT '标签所在模板文件',
  `class_cfg` varchar(100) NOT NULL COMMENT '获取标签数据的类名与方法',
  `cfg` text NOT NULL COMMENT '基础参数配置，比如显示哪些栏目，如何排序等等',
  `extend_cfg` text NOT NULL COMMENT '扩展配置，可以是纯代码、图片，也可以是模板数据',
  `type` varchar(25) NOT NULL COMMENT '调用类型，比如图片、代码等',
  `ifdata` tinyint(4) NOT NULL COMMENT '是否只要原始数据，不要直接输出',
  `hide` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否隐藏',
  `cache_time` int(10) NOT NULL DEFAULT '0' COMMENT '缓存时间',
  `uid` mediumint(7) NOT NULL DEFAULT '0' COMMENT '修改者',
  `create_time` int(10) NOT NULL DEFAULT '0' COMMENT '标签创建时间',
  `update_time` int(10) NOT NULL COMMENT '修改时间',
  `system_id` mediumint(6) NOT NULL DEFAULT '0' COMMENT '所属模块，插件为负数',
  `if_js` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否站外调用,比如APP或小程序或JS,暂时没使用',
  `power_cfg` varchar(255) NOT NULL COMMENT '权限扩展,暂时没使用',
  `view_tpl` text NOT NULL COMMENT '标签的模板代码,暂时没使用',
  `fid` mediumint(5) NOT NULL COMMENT '分类分组,暂时没使用',
  `title` varchar(50) NOT NULL COMMENT '标签名称说明,暂时没,暂时没使用使用',
  `list` int(10) NOT NULL COMMENT '排序值,暂时没使用',
  `ext_sys` smallint(4) NOT NULL COMMENT '扩展字段,关联的系统',
  `ext_id` mediumint(6) NOT NULL COMMENT '扩展字段,关联的系统ID',
  PRIMARY KEY (`id`),
  KEY `module_id` (`system_id`),
  KEY `page` (`pagename`),
  KEY `name` (`name`,`ext_id`,`ext_sys`),
  KEY `ext_id` (`ext_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='用户可以修改的标签,比如圈子黄页' AUTO_INCREMENT=1 ;